modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "warlordsplusplus"
version = "${file.jarVersion}"
displayName = "WarlordsPlusPlus"
logoFile = "examplemod.png"
authors = "ebicep"
description = '''

'''

[[dependencies.warlordsplusplus]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.warlordsplusplus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"